services:
  db:
    image: mariadb:10.6.18
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: iine
    command: --wait-timeout=60

volumes:
  mariadb:
