name: toraiine
version: '${version}'
main: com.toraden.toraiine.Toraiine
api-version: '1.21'

commands:
  iinelist:
    description: player command
  iinetp:
    description: player command
  deliine:
    description: player command
